[build]
  publish = "dist"
  command = "pnpm run build"

[[edge_functions]]
  path = "/fetch/*"
  function = "fetch"

[[redirects]]
  from = "/fetch/*"
  to = "/fetch"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  autoLaunch = false
  command = "pnpm vite"