classDiagram
class JSONBaseDataLabelsGroup~From, T~ {
  <<interface>>
  version: 1
  from: From
  choices: JSONSelectableList#60;JSONDataLabel#60;T#62;#62;
}



class JSONBaseDataLabels {
  <<interface>>
  version: 1
  table: JSONSelectableList#60;JSONTableDataLabelsParameters#62;
}



class BaseDataLabels {
  <<interface>>
  groups: SelectableList#60;AnyBaseDataLabelsGroup, BaseDataLabelsGroups#62;
  table: SelectableList#60;BaseTableDataLabelsParameters#62;
  getList: #40;from: DataLabelsFrom#41; =#62; DataLabel#60;string, string#62;[]
  findIn: #40;     from: DataLabelsFrom,     name: string,     category?: DataCategory   #41; =#62; DataLabel#60;string, string#62; | undefined
  pushTo: #40;     from: DataLabelsFrom,     label: DataLabel   #41; =#62; DataLabel#60;string, string#62; | undefined
}
BaseDataLabels <.. AnyBaseDataLabelsGroup
BaseDataLabels <.. BaseDataLabelsGroups
BaseDataLabels <.. BaseTableDataLabelsParameters


class BaseDataLabelsGroups {
  <<type>>
  [   BaseDropDataLabelsGroup#60;BaseDropIndex#62;,   BaseTestDataLabelsGroup,   BaseZoneDataLabelsGroup ]
}
BaseDataLabelsGroups <.. BaseDropDataLabelsGroup~Drop~
BaseDataLabelsGroups <.. BaseDropIndex
BaseDataLabelsGroups <.. BaseTestDataLabelsGroup
BaseDataLabelsGroups <.. BaseZoneDataLabelsGroup


class AnyBaseDataLabelsGroup {
  <<type>>
  BaseDataLabelsGroups[number]
}
AnyBaseDataLabelsGroup <.. BaseDataLabelsGroups


class BaseDataLabelsGroup~From~ {
  <<interface>>
  from: From
  choices: SelectableList#60;DataLabel#60;string#62;#62;
  saveableChoices: DataLabel#60;string#62;[]
}



class BaseDropDataLabelsGroup~Drop~ {
  <<interface>>
  indexes: SelectableList#60;Drop#62;
}



class BaseTestDataLabelsGroup {
  <<interface>>

}



class BaseZoneDataLabelsGroup {
  <<interface>>

}



class BaseTableDataLabelsParameters {
  <<interface>>
  group: AnyBaseDataLabelsGroup
  dataLabels: DataLabel#60;string#62;[]
  index?: BaseDropIndex
}
BaseTableDataLabelsParameters <.. AnyBaseDataLabelsGroup
BaseTableDataLabelsParameters <.. BaseDropIndex


class JSONMaxidynDataLabelsGroup {
  <<type>>
  JSONMaxidynDataLabelsGroups[number]
}
JSONMaxidynDataLabelsGroup <.. JSONMaxidynDataLabelsGroups


class JSONMaxidynDataLabelsGroups {
  <<type>>
  [   JSONMaxidynDropDataLabelsGroup,   JSONMaxidynTestDataLabelsGroup,   JSONMaxidynZoneDataLabelsGroup ]
}
JSONMaxidynDataLabelsGroups <.. JSONMaxidynDropDataLabelsGroup
JSONMaxidynDataLabelsGroups <.. JSONMaxidynTestDataLabelsGroup
JSONMaxidynDataLabelsGroups <.. JSONMaxidynZoneDataLabelsGroup


class JSONMaxidynDropDataLabelsGroup {
  <<interface>>
  version: 1
  base: JSONBaseDataLabelsGroup#60;'Drop', MaxidynUnitsNames#62;
  distinct: JSONMaxidynDropDataLabelsGroupDistinct
}
JSONMaxidynDropDataLabelsGroup <.. JSONBaseDataLabelsGroup~From, T~
JSONMaxidynDropDataLabelsGroup <.. MaxidynUnitsNames
JSONMaxidynDropDataLabelsGroup <.. JSONMaxidynDropDataLabelsGroupDistinct


class JSONMaxidynDropDataLabelsGroupDistinct {
  <<interface>>
  version: 1
  indexes: JSONSelectableList#60;JSONMaxidynDropIndex#62;
}
JSONMaxidynDropDataLabelsGroupDistinct <.. JSONMaxidynDropIndex


class JSONMaxidynTestDataLabelsGroup {
  <<interface>>
  version: 1
  base: JSONBaseDataLabelsGroup#60;'Point', MaxidynUnitsNames#62;
  distinct: #123;     readonly version: 1   #125;
}
JSONMaxidynTestDataLabelsGroup <.. JSONBaseDataLabelsGroup~From, T~
JSONMaxidynTestDataLabelsGroup <.. MaxidynUnitsNames


class JSONMaxidynTestDataLabelsGroupDistinct {
  <<interface>>
  version: 1
}



class JSONMaxidynZoneDataLabelsGroup {
  <<interface>>
  version: 1
  base: JSONBaseDataLabelsGroup#60;'Zone', MaxidynUnitsNames#62;
  distinct: JSONMaxidynZoneDataLabelsGroupDistinct
}
JSONMaxidynZoneDataLabelsGroup <.. JSONBaseDataLabelsGroup~From, T~
JSONMaxidynZoneDataLabelsGroup <.. MaxidynUnitsNames
JSONMaxidynZoneDataLabelsGroup <.. JSONMaxidynZoneDataLabelsGroupDistinct


class JSONMaxidynZoneDataLabelsGroupDistinct {
  <<interface>>
  version: 1
}



class MaxidynDataLabels {
  <<interface>>
  groups: SelectableList#60;     MaxidynDataLabelsGroup,     MaxidynDataLabelsGroups   #62;
}
MaxidynDataLabels <.. MaxidynDataLabelsGroup
MaxidynDataLabels <.. MaxidynDataLabelsGroups
BaseDataLabels <|-- MaxidynDataLabels

class MaxidynDataLabelsGroup {
  <<type>>
  MaxidynDataLabelsGroups[number]
}
MaxidynDataLabelsGroup <.. MaxidynDataLabelsGroups


class MaxidynDataLabelsGroups {
  <<type>>
  [   MaxidynDropDataLabelsGroup,   MaxidynTestDataLabelsGroup,   MaxidynZoneDataLabelsGroup ]
}
MaxidynDataLabelsGroups <.. MaxidynDropDataLabelsGroup
MaxidynDataLabelsGroups <.. MaxidynTestDataLabelsGroup
MaxidynDataLabelsGroups <.. MaxidynZoneDataLabelsGroup


class MaxidynDropDataLabelsGroup {
  <<interface>>
  indexes: SelectableList#60;MaxidynDropIndex#62;
  toJSON: #40;#41; =#62; JSONMaxidynDropDataLabelsGroup
}
MaxidynDropDataLabelsGroup <.. MaxidynDropIndex


class MaxidynTestDataLabelsGroup {
  <<interface>>
  toJSON: #40;#41; =#62; JSONMaxidynTestDataLabelsGroup
}

BaseTestDataLabelsGroup <|-- MaxidynTestDataLabelsGroup

class MaxidynZoneDataLabelsGroup {
  <<interface>>
  toJSON: #40;#41; =#62; JSONMaxidynZoneDataLabelsGroup
}

BaseZoneDataLabelsGroup <|-- MaxidynZoneDataLabelsGroup

class JSONBaseDropVAny {
  <<type>>
  JSONBaseDrop
}
JSONBaseDropVAny <.. JSONBaseDrop


class JSONBaseDrop {
  <<interface>>
  version: 1
  index: number
  data: JSONDataValue[]
}



class JSONBaseDropIndexVAny {
  <<type>>
  JSONBaseDropIndex
}
JSONBaseDropIndexVAny <.. JSONBaseDropIndex


class JSONBaseDropIndex {
  <<interface>>
  version: 1
  displayedIndex: number
}



class BaseDrop~DropIndex, Point~ {
  <<interface>>
  index: DropIndex
  data: DataValue#60;string#62;[]
  point: Point
  impactData: ImpactData | null
}



class BaseDropIndex {
  <<interface>>
  displayedIndex: number
}



class JSONMaxidynDropVAny {
  <<type>>
  JSONMaxidynDrop
}
JSONMaxidynDropVAny <.. JSONMaxidynDrop


class JSONMaxidynDrop {
  <<interface>>
  version: 1
  base: JSONBaseDrop
  distinct: JSONMaxidynDropDistinct
}
JSONMaxidynDrop <.. JSONBaseDrop
JSONMaxidynDrop <.. JSONMaxidynDropDistinct


class JSONMaxidynDropDistinct {
  <<interface>>
  version: 1
}



class JSONMaxidynDropIndexVAny {
  <<type>>
  JSONMaxidynDropIndex
}
JSONMaxidynDropIndexVAny <.. JSONMaxidynDropIndex


class JSONMaxidynDropIndex {
  <<interface>>
  version: 1
  base: JSONBaseDropIndex
  distinct: JSONMaxidynDropIndexDistinct
}
JSONMaxidynDropIndex <.. JSONBaseDropIndex
JSONMaxidynDropIndex <.. JSONMaxidynDropIndexDistinct


class JSONMaxidynDropIndexDistinct {
  <<interface>>
  version: 1
  type: MaxidynDropType
}
JSONMaxidynDropIndexDistinct <.. MaxidynDropType


class MaxidynDropType {
  <<type>>
  'Training' | 'Averaging'
}



class MaxidynDrop {
  <<interface>>

}



class MaxidynDropIndex {
  <<interface>>
  type: MaxidynDropType
}
MaxidynDropIndex <.. MaxidynDropType
BaseDropIndex <|-- MaxidynDropIndex

class Line {
  <<interface>>
  sortedPoints: BasePoint[]
  addToMap: #40;#41; =#62; void
  update: #40;#41; =#62; void
  remove: #40;#41; =#62; void
}
Line <.. BasePoint~Drop, Zone~


class MaxidynUnitsSkeleton~A, B, C, D, E, F, G~ {
  <<interface>>
  modulus: A
  stiffness: B
  deflection: C
  force: D
  distance: E
  time: F
  percentage: G
}



class PossibleMaxidynModulusUnits {
  <<type>>
  'MPa'
}



class PossibleMaxidynStiffnessUnits {
  <<type>>
  'MN / m'
}



class PossibleMaxidynDeflectionUnits {
  <<type>>
  'mm' | 'um'
}



class PossibleMaxidynForceUnits {
  <<type>>
  'N' | 'kN'
}



class PossibleMaxidynDistanceUnits {
  <<type>>
  'm' | 'km' | 'mi'
}



class PossibleMaxidynTimeUnits {
  <<type>>
  's' | 'ms' | 'us'
}



class PossibleMaxidynPercentageUnits {
  <<type>>
  '%'
}



class JSONMaxidynUnitsVAny {
  <<type>>
  JSONMaxidynUnits
}
JSONMaxidynUnitsVAny <.. JSONMaxidynUnits


class JSONMaxidynUnits {
  <<type>>
  #123; version: 1 #125; & MaxidynUnitsSkeleton#60;   JSONMathUnit#60;PossibleMaxidynModulusUnits#62;,   JSONMathUnit#60;PossibleMaxidynStiffnessUnits#62;,   JSONMathUnit#60;PossibleMaxidynDeflectionUnits#62;,   JSONMathUnit#60;PossibleMaxidynForceUnits#62;,   JSONMathUnit#60;PossibleMaxidynDistanceUnits#62;,   JSONMathUnit#60;PossibleMaxidynTimeUnits#62;,   JSONMathUnit#60;PossibleMaxidynPercentageUnits#62; #62;
}
JSONMaxidynUnits <.. MaxidynUnitsSkeleton~A, B, C, D, E, F, G~
JSONMaxidynUnits <.. PossibleMaxidynModulusUnits
JSONMaxidynUnits <.. PossibleMaxidynStiffnessUnits
JSONMaxidynUnits <.. PossibleMaxidynDeflectionUnits
JSONMaxidynUnits <.. PossibleMaxidynForceUnits
JSONMaxidynUnits <.. PossibleMaxidynDistanceUnits
JSONMaxidynUnits <.. PossibleMaxidynTimeUnits
JSONMaxidynUnits <.. PossibleMaxidynPercentageUnits


class MaxidynMathUnits {
  <<type>>
  MaxidynUnitsSkeleton#60;   MathUnit#60;PossibleMaxidynModulusUnits#62;,   MathUnit#60;PossibleMaxidynStiffnessUnits#62;,   MathUnit#60;PossibleMaxidynDeflectionUnits#62;,   MathUnit#60;PossibleMaxidynForceUnits#62;,   MathUnit#60;PossibleMaxidynDistanceUnits#62;,   MathUnit#60;PossibleMaxidynTimeUnits#62;,   MathUnit#60;PossibleMaxidynPercentageUnits#62; #62;
}
MaxidynMathUnits <.. MaxidynUnitsSkeleton~A, B, C, D, E, F, G~
MaxidynMathUnits <.. PossibleMaxidynModulusUnits
MaxidynMathUnits <.. PossibleMaxidynStiffnessUnits
MaxidynMathUnits <.. PossibleMaxidynDeflectionUnits
MaxidynMathUnits <.. PossibleMaxidynForceUnits
MaxidynMathUnits <.. PossibleMaxidynDistanceUnits
MaxidynMathUnits <.. PossibleMaxidynTimeUnits
MaxidynMathUnits <.. PossibleMaxidynPercentageUnits


class MaxidynUnitsNames {
  <<type>>
  keyof MaxidynUnitsSkeleton#60;any#62;
}
MaxidynUnitsNames <.. MaxidynUnitsSkeleton~A, B, C, D, E, F, G~


class JSONBasePointVAny {
  <<type>>
  JSONBasePoint
}
JSONBasePointVAny <.. JSONBasePoint


class JSONBasePoint {
  <<interface>>
  version: 1
  id: string
  number: number
  index: number
  date: string
  coordinates: mapboxgl.LngLatLike
  data: JSONDataValue[]
  settings: JSONPointSettings
  information: JSONField[]
  drops: JSONMachineDrop[]
}



class BasePoint~Drop, Zone~ {
  <<interface>>
  id: string
  date: Date
  marker: mapboxgl.Marker | null
  icon: Icon | null
  settings: JSONPointSettings
  data: DataValue#60;string#62;[]
  information: Field[]
  drops: Drop[]
  index: number
  number: number
  zone: Zone
  rawDataFile: ArrayBufferLike | null
  getSelectedMathNumber: #40;     groupFrom: DataLabelsFrom,     dataLabel: DataLabel#60;string#62;,     index?: BaseDropIndex | null   #41; =#62; MathNumber | undefined
  getDisplayedString: #40;     groupFrom: DataLabelsFrom,     dataLabel: DataLabel#60;string#62;,     index?: BaseDropIndex | null   #41; =#62; string
  updateColor: #40;#41; =#62; void
  updateText: #40;#41; =#62; void
  updateVisibility: #40;#41; =#62; void
  updatePopup: #40;#41; =#62; void
  addToMap: #40;#41; =#62; void
  checkVisibility: #40;#41; =#62; boolean
  remove: #40;#41; =#62; void
}



class JSONMaxidynPointVAny {
  <<type>>
  JSONMaxidynPoint
}
JSONMaxidynPointVAny <.. JSONMaxidynPoint


class JSONMaxidynPoint {
  <<interface>>
  version: 1
  base: JSONBasePoint
  distinct: JSONMaxidynPointDistinct
}
JSONMaxidynPoint <.. JSONBasePoint
JSONMaxidynPoint <.. JSONMaxidynPointDistinct


class JSONMaxidynPointDistinct {
  <<interface>>
  version: 1
}



class MaxidynPoint {
  <<interface>>

}



class JSONBaseProjectVAny {
  <<type>>
  JSONBaseProject
}
JSONBaseProjectVAny <.. JSONBaseProject


class JSONBaseProject {
  <<interface>>
  version: 1
  name: string
  reports: JSONSelectableList#60;JSONMachineReport#62;
  settings: JSONProjectSettings
  overlays: JSONOverlay[]
  information: JSONField[]
  hardware: JSONField[]
  acquisitionParameters: JSONAcquisitionParameters
}



class BaseProject~Report, MathUnits~ {
  <<interface>>
  name: Field
  information: Field[]
  hardware: Field[]
  reports: SelectableList#60;Report#62;
  units: MathUnits
  settings: BaseProjectSettings
  overlays: Overlay[]
  acquisitionParameters: JSONAcquisitionParameters
  refreshLinesAndOverlays: #40;#41; =#62; void
  setMapStyle: #40;styleIndex: number#41; =#62; void
  fitOnMap: #40;#41; =#62; void
  addToMap: #40;#41; =#62; void
  remove: #40;#41; =#62; void
}
BaseProject~Report, MathUnits~ <.. BaseProjectSettings


class BaseProjectSettings {
  <<interface>>
  arePointsLocked: boolean
}



class JSONMaxidynProjectVAny {
  <<type>>
  JSONMaxidynProject
}
JSONMaxidynProjectVAny <.. JSONMaxidynProject


class JSONMaxidynProject {
  <<interface>>
  version: 1
  machine: 'Maxidyn'
  base: JSONBaseProject
  distinct: JSONMaxidynProjectDistinct
}
JSONMaxidynProject <.. JSONBaseProject
JSONMaxidynProject <.. JSONMaxidynProjectDistinct


class JSONMaxidynProjectDistinct {
  <<interface>>
  version: 1
  units: JSONMaxidynUnits
  bearingParameters: JSONBearingParameters
}
JSONMaxidynProjectDistinct <.. JSONMaxidynUnits


class MaxidynProject {
  <<interface>>
  bearingParameters: JSONBearingParameters
}



class JSONBaseReportVAny {
  <<type>>
  JSONBaseReport
}
JSONBaseReportVAny <.. JSONBaseReport


class JSONBaseReport {
  <<interface>>
  version: 1
  name: string
  zones: JSONMachineZone[]
  settings: JSONReportSettings
  screenshots: number[]
  platform: JSONField[]
  information: JSONField[]
  dataLabels: JSONBaseDataLabels
  thresholds: JSONBaseThresholdsSettings
}
JSONBaseReport <.. JSONBaseDataLabels
JSONBaseReport <.. JSONBaseThresholdsSettings


class JSONBaseThresholdsSettings {
  <<interface>>
  version: 1
  colors: JSONThresholdColors
  inputs: JSONThresholdInputs
}



class BaseReport~Project, Zone, DataLabels, Thresholds~ {
  <<interface>>
  name: Field
  line: Line
  zones: Zone[]
  screenshots: string[]
  dataLabels: DataLabels
  thresholds: Thresholds
  settings: JSONReportSettings
  platform: Field[]
  information: Field[]
  project: Project
  isOnMap: boolean
  fitOnMap: #40;#41; =#62; void
  addToMap: #40;#41; =#62; void
  remove: #40;#41; =#62; void
}
BaseReport~Project, Zone, DataLabels, Thresholds~ <.. Line


class JSONMaxidynReportVAny {
  <<type>>
  JSONMaxidynReport
}
JSONMaxidynReportVAny <.. JSONMaxidynReport


class JSONMaxidynReport {
  <<interface>>
  version: 1
  base: JSONBaseReport
  distinct: JSONMaxidynReportDistinct
}
JSONMaxidynReport <.. JSONBaseReport
JSONMaxidynReport <.. JSONMaxidynReportDistinct


class JSONMaxidynReportDistinct {
  <<interface>>
  version: 1
  dataLabels: JSONSelectableList#60;     JSONMaxidynDataLabelsGroup,     JSONMaxidynDataLabelsGroups   #62;
  thresholds: JSONMaxidynThresholdsConfigurations
}
JSONMaxidynReportDistinct <.. JSONMaxidynDataLabelsGroup
JSONMaxidynReportDistinct <.. JSONMaxidynDataLabelsGroups
JSONMaxidynReportDistinct <.. JSONMaxidynThresholdsConfigurations


class MaxidynReport {
  <<interface>>
  addZone: #40;#41; =#62; void
}



class BaseThresholds~ThresholdsGroups~ {
  <<interface>>
  groups: ThresholdsGroups
  colors: JSONThresholdColors
  inputs: JSONThresholdInputs
}



class BaseThresholdsGroups {
  <<type>>
  MachineUnitsSkeleton#60;ThresholdsGroup#60;string#62;#62;
}



class MaxidynThresholds {
  <<interface>>
  groups: MaxidynThresholdsGroups
}
MaxidynThresholds <.. MaxidynThresholdsGroups


class MaxidynThresholdsGroups {
  <<type>>
  MaxidynUnitsSkeleton#60;ThresholdsGroup#60;string#62;#62;
}
MaxidynThresholdsGroups <.. MaxidynUnitsSkeleton~A, B, C, D, E, F, G~


class JSONMaxidynThresholdsConfigurationsVAny {
  <<type>>
  JSONMaxidynThresholdsConfigurations
}
JSONMaxidynThresholdsConfigurationsVAny <.. JSONMaxidynThresholdsConfigurations


class JSONMaxidynThresholdsConfigurations {
  <<type>>
  #123;   version: 1 #125; & MaxidynUnitsSkeleton#60;JSONDistinctThresholdsConfiguration#62;
}
JSONMaxidynThresholdsConfigurations <.. MaxidynUnitsSkeleton~A, B, C, D, E, F, G~


class MaxidynObject~T~ {
  <<interface>>

}



class BaseObject~T~ {
  <<interface>>
  toBaseJSON: #40;#41; =#62; T
}



class JSONBaseZoneVAny {
  <<type>>
  JSONBaseZone
}
JSONBaseZoneVAny <.. JSONBaseZone


class JSONBaseZone {
  <<interface>>
  version: 1
  name: string
  points: JSONMachinePoint[]
  settings: JSONZoneSettings
}



class BaseZone~Point, Report~ {
  <<interface>>
  points: Point[]
  settings: JSONZoneSettings
  name: string
  report: Report
  data: DataValue#60;string#62;[]
  init: #40;#41; =#62; void
  clean: #40;#41; =#62; void
}



class MaxidynZoneCreatorParameters {
  <<interface>>
  report: MaxidynReport
}
MaxidynZoneCreatorParameters <.. MaxidynReport


class JSONMaxidynZoneVAny {
  <<type>>
  JSONMaxidynZone
}
JSONMaxidynZoneVAny <.. JSONMaxidynZone


class JSONMaxidynZone {
  <<interface>>
  version: 1
  base: JSONBaseZone
  distinct: JSONMaxidynZoneDistinct
}
JSONMaxidynZone <.. JSONBaseZone
JSONMaxidynZone <.. JSONMaxidynZoneDistinct


class JSONMaxidynZoneDistinct {
  <<interface>>
  version: 1
}



class MaxidynZone {
  <<interface>>

}



class MaxidynExporter {
  <<interface>>
  export: #40;project: MaxidynProject#41; =#62; Promise#60;File#62;
}



