classDiagram
class JSONBaseDataLabelsGroup~From, T~ {
  <<interface>>
  version: 1
  from: From
  choices: JSONSelectableList#60;JSONDataLabel#60;T#62;#62;
}



class JSONBaseDataLabels {
  <<interface>>
  version: 1
  table: JSONSelectableList#60;JSONTableDataLabelsParameters#62;
}



class BaseDataLabels {
  <<interface>>
  groups: SelectableList#60;AnyBaseDataLabelsGroup, BaseDataLabelsGroups#62;
  table: SelectableList#60;BaseTableDataLabelsParameters#62;
  getList: #40;from: DataLabelsFrom#41; =#62; DataLabel#60;string, string#62;[]
  findIn: #40;     from: DataLabelsFrom,     name: string,     category?: DataCategory   #41; =#62; DataLabel#60;string, string#62; | undefined
  pushTo: #40;     from: DataLabelsFrom,     label: DataLabel   #41; =#62; DataLabel#60;string, string#62; | undefined
}
BaseDataLabels <.. AnyBaseDataLabelsGroup
BaseDataLabels <.. BaseDataLabelsGroups
BaseDataLabels <.. BaseTableDataLabelsParameters


class BaseDataLabelsGroups {
  <<type>>
  [   BaseDropDataLabelsGroup#60;BaseDropIndex#62;,   BaseTestDataLabelsGroup,   BaseZoneDataLabelsGroup ]
}
BaseDataLabelsGroups <.. BaseDropDataLabelsGroup~Drop~
BaseDataLabelsGroups <.. BaseDropIndex
BaseDataLabelsGroups <.. BaseTestDataLabelsGroup
BaseDataLabelsGroups <.. BaseZoneDataLabelsGroup


class AnyBaseDataLabelsGroup {
  <<type>>
  BaseDataLabelsGroups[number]
}
AnyBaseDataLabelsGroup <.. BaseDataLabelsGroups


class BaseDataLabelsGroup~From~ {
  <<interface>>
  from: From
  choices: SelectableList#60;DataLabel#60;string#62;#62;
  saveableChoices: DataLabel#60;string#62;[]
}



class BaseDropDataLabelsGroup~Drop~ {
  <<interface>>
  indexes: SelectableList#60;Drop#62;
}



class BaseTestDataLabelsGroup {
  <<interface>>

}



class BaseZoneDataLabelsGroup {
  <<interface>>

}



class BaseTableDataLabelsParameters {
  <<interface>>
  group: AnyBaseDataLabelsGroup
  dataLabels: DataLabel#60;string#62;[]
  index?: BaseDropIndex
}
BaseTableDataLabelsParameters <.. AnyBaseDataLabelsGroup
BaseTableDataLabelsParameters <.. BaseDropIndex


class JSONHeavydynDataLabelsGroup {
  <<type>>
  JSONHeavydynDataLabelsGroups[number]
}
JSONHeavydynDataLabelsGroup <.. JSONHeavydynDataLabelsGroups


class JSONHeavydynDataLabelsGroups {
  <<type>>
  [   JSONHeavydynDropDataLabelsGroup,   JSONHeavydynTestDataLabelsGroup,   JSONHeavydynZoneDataLabelsGroup ]
}
JSONHeavydynDataLabelsGroups <.. JSONHeavydynDropDataLabelsGroup
JSONHeavydynDataLabelsGroups <.. JSONHeavydynTestDataLabelsGroup
JSONHeavydynDataLabelsGroups <.. JSONHeavydynZoneDataLabelsGroup


class JSONHeavydynDropDataLabelsGroup {
  <<interface>>
  version: 1
  base: JSONBaseDataLabelsGroup#60;'Drop', HeavydynUnitsNames#62;
  distinct: JSONHeavydynDropDataLabelsGroupDistinct
}
JSONHeavydynDropDataLabelsGroup <.. JSONBaseDataLabelsGroup~From, T~
JSONHeavydynDropDataLabelsGroup <.. HeavydynUnitsNames
JSONHeavydynDropDataLabelsGroup <.. JSONHeavydynDropDataLabelsGroupDistinct


class JSONHeavydynDropDataLabelsGroupDistinct {
  <<interface>>
  version: 1
  indexes: JSONSelectableList#60;JSONHeavydynDropIndex#62;
  sequenceName: string
}
JSONHeavydynDropDataLabelsGroupDistinct <.. JSONHeavydynDropIndex


class JSONHeavydynTestDataLabelsGroup {
  <<interface>>
  version: 1
  base: JSONBaseDataLabelsGroup#60;'Point', HeavydynUnitsNames#62;
  distinct: #123;     readonly version: 1   #125;
}
JSONHeavydynTestDataLabelsGroup <.. JSONBaseDataLabelsGroup~From, T~
JSONHeavydynTestDataLabelsGroup <.. HeavydynUnitsNames


class JSONHeavydynTestDataLabelsGroupDistinct {
  <<interface>>
  version: 1
}



class JSONHeavydynZoneDataLabelsGroup {
  <<interface>>
  version: 1
  base: JSONBaseDataLabelsGroup#60;'Zone', HeavydynUnitsNames#62;
  distinct: JSONHeavydynZoneDataLabelsGroupDistinct
}
JSONHeavydynZoneDataLabelsGroup <.. JSONBaseDataLabelsGroup~From, T~
JSONHeavydynZoneDataLabelsGroup <.. HeavydynUnitsNames
JSONHeavydynZoneDataLabelsGroup <.. JSONHeavydynZoneDataLabelsGroupDistinct


class JSONHeavydynZoneDataLabelsGroupDistinct {
  <<interface>>
  version: 1
}



class HeavydynDataLabels {
  <<interface>>
  groups: SelectableList#60;     HeavydynDataLabelsGroup,     HeavydynDataLabelsGroups   #62;
}
HeavydynDataLabels <.. HeavydynDataLabelsGroup
HeavydynDataLabels <.. HeavydynDataLabelsGroups
BaseDataLabels <|-- HeavydynDataLabels

class HeavydynDataLabelsGroup {
  <<type>>
  HeavydynDataLabelsGroups[number]
}
HeavydynDataLabelsGroup <.. HeavydynDataLabelsGroups


class HeavydynDataLabelsGroups {
  <<type>>
  [   HeavydynDropDataLabelsGroup,   HeavydynTestDataLabelsGroup,   HeavydynZoneDataLabelsGroup ]
}
HeavydynDataLabelsGroups <.. HeavydynDropDataLabelsGroup
HeavydynDataLabelsGroups <.. HeavydynTestDataLabelsGroup
HeavydynDataLabelsGroups <.. HeavydynZoneDataLabelsGroup


class HeavydynDropDataLabelsGroup {
  <<interface>>
  indexes: SelectableList#60;HeavydynDropIndex#62;
  sequenceName: string
  toJSON: #40;#41; =#62; JSONHeavydynDropDataLabelsGroup
}
HeavydynDropDataLabelsGroup <.. HeavydynDropIndex


class HeavydynTestDataLabelsGroup {
  <<interface>>
  toJSON: #40;#41; =#62; JSONHeavydynTestDataLabelsGroup
}

BaseTestDataLabelsGroup <|-- HeavydynTestDataLabelsGroup

class HeavydynZoneDataLabelsGroup {
  <<interface>>
  toJSON: #40;#41; =#62; JSONHeavydynZoneDataLabelsGroup
}

BaseZoneDataLabelsGroup <|-- HeavydynZoneDataLabelsGroup

class JSONBaseDropVAny {
  <<type>>
  JSONBaseDrop
}
JSONBaseDropVAny <.. JSONBaseDrop


class JSONBaseDrop {
  <<interface>>
  version: 1
  index: number
  data: JSONDataValue[]
}



class JSONBaseDropIndexVAny {
  <<type>>
  JSONBaseDropIndex
}
JSONBaseDropIndexVAny <.. JSONBaseDropIndex


class JSONBaseDropIndex {
  <<interface>>
  version: 1
  displayedIndex: number
}



class BaseDrop~DropIndex, Point~ {
  <<interface>>
  index: DropIndex
  data: DataValue#60;string#62;[]
  point: Point
  impactData: ImpactData | null
}



class BaseDropIndex {
  <<interface>>
  displayedIndex: number
}



class JSONHeavydynDropVAny {
  <<type>>
  JSONHeavydynDrop
}
JSONHeavydynDropVAny <.. JSONHeavydynDrop


class JSONHeavydynDrop {
  <<interface>>
  version: 1
  base: JSONBaseDrop
  distinct: JSONHeavydynDropDistinct
}
JSONHeavydynDrop <.. JSONBaseDrop
JSONHeavydynDrop <.. JSONHeavydynDropDistinct


class JSONHeavydynDropDistinct {
  <<interface>>
  version: 1
}



class JSONHeavydynDropIndexVAny {
  <<type>>
  JSONHeavydynDropIndex
}
JSONHeavydynDropIndexVAny <.. JSONHeavydynDropIndex


class JSONHeavydynDropIndex {
  <<interface>>
  version: 1
  base: JSONBaseDropIndex
  distinct: JSONHeavydynDropIndexDistinct
}
JSONHeavydynDropIndex <.. JSONBaseDropIndex
JSONHeavydynDropIndex <.. JSONHeavydynDropIndexDistinct


class JSONHeavydynDropIndexDistinct {
  <<interface>>
  version: 1
  type: HeavydynDropType
  value: number
  unit: string
}
JSONHeavydynDropIndexDistinct <.. HeavydynDropType


class HeavydynDropType {
  <<type>>
  'Distance' | 'Time' | 'Force' | 'Height'
}



class HeavydynDrop {
  <<interface>>

}



class HeavydynDropIndex {
  <<interface>>
  type: HeavydynDropType
  value: MathNumber
}
HeavydynDropIndex <.. HeavydynDropType
BaseDropIndex <|-- HeavydynDropIndex

class Line {
  <<interface>>
  sortedPoints: BasePoint[]
  addToMap: #40;#41; =#62; void
  update: #40;#41; =#62; void
  remove: #40;#41; =#62; void
}
Line <.. BasePoint~Drop, Zone~


class HeavydynUnitsSkeleton~A, B, C, D, E, F, G, H~ {
  <<interface>>
  deflection: A
  force: B
  temperature: C
  distance: D
  time: E
  modulus: F
  cumSum: G
  radius: H
}



class HeavydynUnitsSkeletonV1~A, B, C, D, E, F, G~ {
  <<interface>>
  deflection: A
  force: B
  temperature: C
  distance: D
  time: E
  modulus: F
  cumSum: G
}



class HeavydynUnitsNames {
  <<type>>
  keyof HeavydynUnitsSkeleton#60;any#62;
}
HeavydynUnitsNames <.. HeavydynUnitsSkeleton~A, B, C, D, E, F, G, H~


class PossibleHeavydynDeflectionUnits {
  <<type>>
  'mm' | '1/100 mm' | 'um'
}



class PossibleHeavydynForceUnits {
  <<type>>
  'N' | 'kN' | 'lbs'
}



class PossibleHeavydynTemperatureUnits {
  <<type>>
  '°C' | '°F' | 'K'
}



class PossibleHeavydynDistanceUnits {
  <<type>>
  'm' | 'km' | 'mi'
}



class PossibleHeavydynTimeUnits {
  <<type>>
  's' | 'ms' | 'us'
}



class PossibleHeavydynModulusUnits {
  <<type>>
  'MPa'
}



class PossibleHeavydynRadiusUnits {
  <<type>>
  'm' | 'km' | 'mi'
}



class JSONHeavydynUnitsVAny {
  <<type>>
  JSONHeavydynUnits | JSONHeavydynUnitsV1
}
JSONHeavydynUnitsVAny <.. JSONHeavydynUnits
JSONHeavydynUnitsVAny <.. JSONHeavydynUnitsV1


class JSONHeavydynUnits {
  <<type>>
  #123; version: 2 #125; & HeavydynUnitsSkeleton#60;   JSONMathUnit#60;PossibleHeavydynDeflectionUnits#62;,   JSONMathUnit#60;PossibleHeavydynForceUnits#62;,   JSONMathUnit#60;PossibleHeavydynTemperatureUnits#62;,   JSONMathUnit#60;PossibleHeavydynDistanceUnits#62;,   JSONMathUnit#60;PossibleHeavydynTimeUnits#62;,   JSONMathUnit#60;PossibleHeavydynModulusUnits#62;,   JSONMathUnit#60;''#62;,   JSONMathUnit#60;PossibleHeavydynRadiusUnits#62; #62;
}
JSONHeavydynUnits <.. HeavydynUnitsSkeleton~A, B, C, D, E, F, G, H~
JSONHeavydynUnits <.. PossibleHeavydynDeflectionUnits
JSONHeavydynUnits <.. PossibleHeavydynForceUnits
JSONHeavydynUnits <.. PossibleHeavydynTemperatureUnits
JSONHeavydynUnits <.. PossibleHeavydynDistanceUnits
JSONHeavydynUnits <.. PossibleHeavydynTimeUnits
JSONHeavydynUnits <.. PossibleHeavydynModulusUnits
JSONHeavydynUnits <.. PossibleHeavydynRadiusUnits


class JSONHeavydynUnitsV1 {
  <<type>>
  #123; version: 1 #125; & HeavydynUnitsSkeletonV1#60;   JSONMathUnit#60;PossibleHeavydynDeflectionUnits#62;,   JSONMathUnit#60;PossibleHeavydynForceUnits#62;,   JSONMathUnit#60;PossibleHeavydynTemperatureUnits#62;,   JSONMathUnit#60;PossibleHeavydynDistanceUnits#62;,   JSONMathUnit#60;PossibleHeavydynTimeUnits#62;,   JSONMathUnit#60;PossibleHeavydynModulusUnits#62;,   JSONMathUnit#60;''#62; #62;
}
JSONHeavydynUnitsV1 <.. HeavydynUnitsSkeletonV1~A, B, C, D, E, F, G~
JSONHeavydynUnitsV1 <.. PossibleHeavydynDeflectionUnits
JSONHeavydynUnitsV1 <.. PossibleHeavydynForceUnits
JSONHeavydynUnitsV1 <.. PossibleHeavydynTemperatureUnits
JSONHeavydynUnitsV1 <.. PossibleHeavydynDistanceUnits
JSONHeavydynUnitsV1 <.. PossibleHeavydynTimeUnits
JSONHeavydynUnitsV1 <.. PossibleHeavydynModulusUnits


class HeavydynMathUnits {
  <<type>>
  HeavydynUnitsSkeleton#60;   MathUnit#60;PossibleHeavydynDeflectionUnits#62;,   MathUnit#60;PossibleHeavydynForceUnits#62;,   MathUnit#60;PossibleHeavydynTemperatureUnits#62;,   MathUnit#60;PossibleHeavydynDistanceUnits#62;,   MathUnit#60;PossibleHeavydynTimeUnits#62;,   MathUnit#60;PossibleHeavydynModulusUnits#62;,   MathUnit#60;''#62;,   MathUnit#60;PossibleHeavydynRadiusUnits#62; #62;
}
HeavydynMathUnits <.. HeavydynUnitsSkeleton~A, B, C, D, E, F, G, H~
HeavydynMathUnits <.. PossibleHeavydynDeflectionUnits
HeavydynMathUnits <.. PossibleHeavydynForceUnits
HeavydynMathUnits <.. PossibleHeavydynTemperatureUnits
HeavydynMathUnits <.. PossibleHeavydynDistanceUnits
HeavydynMathUnits <.. PossibleHeavydynTimeUnits
HeavydynMathUnits <.. PossibleHeavydynModulusUnits
HeavydynMathUnits <.. PossibleHeavydynRadiusUnits


class JSONBasePointVAny {
  <<type>>
  JSONBasePoint
}
JSONBasePointVAny <.. JSONBasePoint


class JSONBasePoint {
  <<interface>>
  version: 1
  id: string
  number: number
  index: number
  date: string
  coordinates: mapboxgl.LngLatLike
  data: JSONDataValue[]
  settings: JSONPointSettings
  information: JSONField[]
  drops: JSONMachineDrop[]
}



class BasePoint~Drop, Zone~ {
  <<interface>>
  id: string
  date: Date
  marker: mapboxgl.Marker | null
  icon: Icon | null
  settings: JSONPointSettings
  data: DataValue#60;string#62;[]
  information: Field[]
  drops: Drop[]
  index: number
  number: number
  zone: Zone
  rawDataFile: ArrayBufferLike | null
  getSelectedMathNumber: #40;     groupFrom: DataLabelsFrom,     dataLabel: DataLabel#60;string#62;,     index?: BaseDropIndex | null   #41; =#62; MathNumber | undefined
  getDisplayedString: #40;     groupFrom: DataLabelsFrom,     dataLabel: DataLabel#60;string#62;,     index?: BaseDropIndex | null   #41; =#62; string
  updateColor: #40;#41; =#62; void
  updateText: #40;#41; =#62; void
  updateVisibility: #40;#41; =#62; void
  updatePopup: #40;#41; =#62; void
  addToMap: #40;#41; =#62; void
  checkVisibility: #40;#41; =#62; boolean
  remove: #40;#41; =#62; void
}



class JSONHeavydynPointVAny {
  <<type>>
  JSONHeavydynPoint
}
JSONHeavydynPointVAny <.. JSONHeavydynPoint


class JSONHeavydynPoint {
  <<interface>>
  version: 1
  base: JSONBasePoint
  distinct: JSONHeavydynPointDistinct
}
JSONHeavydynPoint <.. JSONBasePoint
JSONHeavydynPoint <.. JSONHeavydynPointDistinct


class JSONHeavydynPointDistinct {
  <<interface>>
  version: 1
}



class HeavydynPoint {
  <<interface>>

}



class JSONBaseProjectVAny {
  <<type>>
  JSONBaseProject
}
JSONBaseProjectVAny <.. JSONBaseProject


class JSONBaseProject {
  <<interface>>
  version: 1
  name: string
  reports: JSONSelectableList#60;JSONMachineReport#62;
  settings: JSONProjectSettings
  overlays: JSONOverlay[]
  information: JSONField[]
  hardware: JSONField[]
  acquisitionParameters: JSONAcquisitionParameters
}



class BaseProject~Report, MathUnits~ {
  <<interface>>
  name: Field
  information: Field[]
  hardware: Field[]
  reports: SelectableList#60;Report#62;
  units: MathUnits
  settings: BaseProjectSettings
  overlays: Overlay[]
  acquisitionParameters: JSONAcquisitionParameters
  refreshLinesAndOverlays: #40;#41; =#62; void
  setMapStyle: #40;styleIndex: number#41; =#62; void
  fitOnMap: #40;#41; =#62; void
  addToMap: #40;#41; =#62; void
  remove: #40;#41; =#62; void
}
BaseProject~Report, MathUnits~ <.. BaseProjectSettings


class BaseProjectSettings {
  <<interface>>
  arePointsLocked: boolean
}



class JSONHeavydynCorrectionParametersVAny {
  <<type>>
  JSONHeavydynCorrectionParameters
}
JSONHeavydynCorrectionParametersVAny <.. JSONHeavydynCorrectionParameters


class JSONHeavydynCorrectionParameters {
  <<interface>>
  version: 1
  load: JSONHeavydynLoadCorrectionParameters
  temperature: JSONHeavydynTemperatureCorrectionParameters
}
JSONHeavydynCorrectionParameters <.. JSONHeavydynLoadCorrectionParameters
JSONHeavydynCorrectionParameters <.. JSONHeavydynTemperatureCorrectionParameters


class JSONHeavydynLoadCorrectionParametersVAny {
  <<type>>
  | JSONHeavydynLoadCorrectionParametersV1   | JSONHeavydynLoadCorrectionParameters
}
JSONHeavydynLoadCorrectionParametersVAny <.. JSONHeavydynLoadCorrectionParametersV1
JSONHeavydynLoadCorrectionParametersVAny <.. JSONHeavydynLoadCorrectionParameters


class JSONHeavydynLoadCorrectionParametersV1 {
  <<interface>>
  version: 1
  active: boolean
  loadReferenceSource: LoadSourceValue
  customValue: number
}



class JSONHeavydynLoadCorrectionParameters {
  <<interface>>
  version: 2
  active: boolean
  source: LoadSourceValue
  customValue: number
}



class JSONHeavydynTemperatureCorrectionParametersVAny {
  <<type>>
  | JSONHeavydynTemperatureCorrectionParametersV1   | JSONHeavydynTemperatureCorrectionParameters
}
JSONHeavydynTemperatureCorrectionParametersVAny <.. JSONHeavydynTemperatureCorrectionParametersV1
JSONHeavydynTemperatureCorrectionParametersVAny <.. JSONHeavydynTemperatureCorrectionParameters


class JSONHeavydynTemperatureCorrectionParametersV1 {
  <<interface>>
  version: 1
  active: boolean
  temperatureFromSource: TemperatureSourceValue
  average: TemperatureAverageValue
  customValue: number
  temperatureTo: number
  structureType: number
}



class JSONHeavydynTemperatureCorrectionParameters {
  <<interface>>
  version: 2
  active: boolean
  source: TemperatureSourceValue
  average: TemperatureAverageValue
  customValue: number
  reference: number
  structureType: number
}



class HeavydynCorrectionParameters {
  <<interface>>
  load: HeavydynLoadCorrectionParameters
  temperature: HeavydynTemperatureCorrectionParameters
}
HeavydynCorrectionParameters <.. HeavydynLoadCorrectionParameters
HeavydynCorrectionParameters <.. HeavydynTemperatureCorrectionParameters


class HeavydynLoadCorrectionParameters {
  <<interface>>
  active: boolean
  source: SelectableList#60;LoadSourceValue, LoadSourceList#62;
  customValue: MathNumber
}



class HeavydynTemperatureCorrectionParameters {
  <<interface>>
  active: boolean
  source: SelectableList#60;TemperatureSourceValue, TemperatureSourceList#62;
  average: SelectableList#60;TemperatureAverageValue, TemperatureAverageList#62;
  customValue: MathNumber
  reference: MathNumber
  structureType: SelectableList#60;     TemperatureStructureTypeValue,     TemperatureStructureTypeList   #62;
}



class JSONHeavydynProjectVAny {
  <<type>>
  JSONHeavydynProject
}
JSONHeavydynProjectVAny <.. JSONHeavydynProject


class JSONHeavydynProject {
  <<interface>>
  version: 1
  machine: 'Heavydyn'
  base: JSONBaseProject
  distinct: JSONHeavydynProjectDistinct
}
JSONHeavydynProject <.. JSONBaseProject
JSONHeavydynProject <.. JSONHeavydynProjectDistinct


class JSONHeavydynProjectDistinct {
  <<interface>>
  version: 1
  units: JSONHeavydynUnits
  calibrations: JSONHeavydynCalibrations
  correctionParameters: JSONHeavydynCorrectionParameters
}
JSONHeavydynProjectDistinct <.. JSONHeavydynUnits
JSONHeavydynProjectDistinct <.. JSONHeavydynCalibrations
JSONHeavydynProjectDistinct <.. JSONHeavydynCorrectionParameters


class JSONHeavydynCalibrations {
  <<interface>>
  version: 1
  date: string
  dPlate: number
  channels: JSONChannel[]
  sensors: JSONSensor[]
}



class HeavydynProject {
  <<interface>>
  calibrations: HeavydynCalibrations
  correctionParameters: HeavydynCorrectionParameters
}
HeavydynProject <.. HeavydynCalibrations
HeavydynProject <.. HeavydynCorrectionParameters


class HeavydynCalibrations {
  <<interface>>
  date: Date
  dPlate: number
  channels: JSONChannel[]
  sensors: JSONSensor[]
}



class JSONBaseReportVAny {
  <<type>>
  JSONBaseReport
}
JSONBaseReportVAny <.. JSONBaseReport


class JSONBaseReport {
  <<interface>>
  version: 1
  name: string
  zones: JSONMachineZone[]
  settings: JSONReportSettings
  screenshots: number[]
  platform: JSONField[]
  information: JSONField[]
  dataLabels: JSONBaseDataLabels
  thresholds: JSONBaseThresholdsSettings
}
JSONBaseReport <.. JSONBaseDataLabels
JSONBaseReport <.. JSONBaseThresholdsSettings


class JSONBaseThresholdsSettings {
  <<interface>>
  version: 1
  colors: JSONThresholdColors
  inputs: JSONThresholdInputs
}



class BaseReport~Project, Zone, DataLabels, Thresholds~ {
  <<interface>>
  name: Field
  line: Line
  zones: Zone[]
  screenshots: string[]
  dataLabels: DataLabels
  thresholds: Thresholds
  settings: JSONReportSettings
  platform: Field[]
  information: Field[]
  project: Project
  isOnMap: boolean
  fitOnMap: #40;#41; =#62; void
  addToMap: #40;#41; =#62; void
  remove: #40;#41; =#62; void
}
BaseReport~Project, Zone, DataLabels, Thresholds~ <.. Line


class JSONHeavydynReportVAny {
  <<type>>
  JSONHeavydynReport
}
JSONHeavydynReportVAny <.. JSONHeavydynReport


class JSONHeavydynReport {
  <<interface>>
  version: 1
  base: JSONBaseReport
  distinct: JSONHeavydynReportDistinct
}
JSONHeavydynReport <.. JSONBaseReport
JSONHeavydynReport <.. JSONHeavydynReportDistinct


class JSONHeavydynReportDistinct {
  <<interface>>
  version: 1
  dataLabels: JSONSelectableList#60;     JSONHeavydynDataLabelsGroup,     JSONHeavydynDataLabelsGroups   #62;
  thresholds: JSONHeavydynThresholdsConfigurations
}
JSONHeavydynReportDistinct <.. JSONHeavydynDataLabelsGroup
JSONHeavydynReportDistinct <.. JSONHeavydynDataLabelsGroups
JSONHeavydynReportDistinct <.. JSONHeavydynThresholdsConfigurations


class HeavydynReport {
  <<interface>>
  addZone: #40;#41; =#62; void
}



class BaseThresholds~ThresholdsGroups~ {
  <<interface>>
  groups: ThresholdsGroups
  colors: JSONThresholdColors
  inputs: JSONThresholdInputs
}



class BaseThresholdsGroups {
  <<type>>
  MachineUnitsSkeleton#60;ThresholdsGroup#60;string#62;#62;
}



class HeavydynThresholds {
  <<interface>>
  groups: HeavydynThresholdsGroups
}
HeavydynThresholds <.. HeavydynThresholdsGroups


class HeavydynThresholdsGroups {
  <<type>>
  HeavydynUnitsSkeleton#60;ThresholdsGroup#60;string#62;#62;
}
HeavydynThresholdsGroups <.. HeavydynUnitsSkeleton~A, B, C, D, E, F, G, H~


class JSONHeavydynThresholdsConfigurationsVAny {
  <<type>>
  | JSONHeavydynThresholdsConfigurations   | JSONHeavydynThresholdsConfigurationsV1
}
JSONHeavydynThresholdsConfigurationsVAny <.. JSONHeavydynThresholdsConfigurations
JSONHeavydynThresholdsConfigurationsVAny <.. JSONHeavydynThresholdsConfigurationsV1


class JSONHeavydynThresholdsConfigurations {
  <<type>>
  #123;   version: 2 #125; & HeavydynUnitsSkeleton#60;JSONDistinctThresholdsConfiguration#62;
}
JSONHeavydynThresholdsConfigurations <.. HeavydynUnitsSkeleton~A, B, C, D, E, F, G, H~


class JSONHeavydynThresholdsConfigurationsV1 {
  <<type>>
  #123;   version: 1 #125; & HeavydynUnitsSkeletonV1#60;JSONDistinctThresholdsConfiguration#62;
}
JSONHeavydynThresholdsConfigurationsV1 <.. HeavydynUnitsSkeletonV1~A, B, C, D, E, F, G~


class HeavydynObject~T~ {
  <<interface>>

}



class BaseObject~T~ {
  <<interface>>
  toBaseJSON: #40;#41; =#62; T
}



class JSONBaseZoneVAny {
  <<type>>
  JSONBaseZone
}
JSONBaseZoneVAny <.. JSONBaseZone


class JSONBaseZone {
  <<interface>>
  version: 1
  name: string
  points: JSONMachinePoint[]
  settings: JSONZoneSettings
}



class BaseZone~Point, Report~ {
  <<interface>>
  points: Point[]
  settings: JSONZoneSettings
  name: string
  report: Report
  data: DataValue#60;string#62;[]
  init: #40;#41; =#62; void
  clean: #40;#41; =#62; void
}



class HeavydynZoneCreatorParameters {
  <<interface>>
  report: HeavydynReport
}
HeavydynZoneCreatorParameters <.. HeavydynReport


class JSONHeavydynZoneVAny {
  <<type>>
  JSONHeavydynZone
}
JSONHeavydynZoneVAny <.. JSONHeavydynZone


class JSONHeavydynZone {
  <<interface>>
  version: 1
  base: JSONBaseZone
  distinct: JSONHeavydynZoneDistinct
}
JSONHeavydynZone <.. JSONBaseZone
JSONHeavydynZone <.. JSONHeavydynZoneDistinct


class JSONHeavydynZoneDistinct {
  <<interface>>
  version: 1
}



class HeavydynZone {
  <<interface>>

}



class HeavydynExporter {
  <<interface>>
  export: #40;project: HeavydynProject#41; =#62; Promise#60;File#62;
}



